RENAME TABLE DECISIONS TO VOTINGS, DECISION_OPTION_MAPPING TO VOTING_OPTION_MAPPING;
ALTER TABLE VOTING_OPTION_MAPPING CHANGE decision_id voting_id bigint;
ALTER TABLE VOTES CHANGE decision_option_id voting_option_id bigint;